### ISSUE TITLE
Не получается запустить

### ISSUE THREAD

**Issue by spvik** [gihar/quik-telegram-bot#1]
День добрый не могу в квике запустить ваш скрипт, ссылается, что не найдена библиотека ssl, скачал luasec, но не знаю, что с ним делать, скомпилировать не  получается, куча ошибок.

**Comment by gihar** [comment]
Чтобы установить luasec нужен OpenSSL. Путь к нему нужно указать при установке luasec. OpenSSL можно взять тут. https://slproweb.com/products/Win32OpenSSL.html
Еще нужен С-компилятор. Я использовал тот, который из VC++ 2010 Express. Установку luasec нужно запускать из консоли Visual Studio иначе компилироваться библиотеки не будут.

Но вообще можно самому и не компилировать, а взять готовые ssl.dll и там еще две dll нужны, на память не помню какие, и положить их в папку, куда QUIK установлен.

Если всё ж не получиться запустить бота, пишите сюда, придумаю как дать вам эти dll.

**Comment by spvik** [comment]
две библиотеки которые нужны это наверно libssl32, ssleay32, не получается скомпилировать эту dll, нашел готовые уже ssl.dll, но они не подходят, проект в квике не запускается, как нибудь можете скинуть вашу готовую библиотеку

**Comment by gihar** [comment]
Добавил к проекту готовые dll. Попробуйте положить их в папку с квиком. Должно запуститься. Если получиться сообщите.

**Comment by spvik** [comment]
.\lua-bot-api.lua:19: module 'ssl.https' not found:
    no field package.preload['ssl.https']

вот что пишет терминал
библиотеки скопировал, везде где только можно

**Comment by spvik** [comment]
разобрался со структурами папок вроде эта ошибка, вот только библиотеке json которая рекомендуют к lua-bot-api, ссылка не доступна, из интернета несколько пробовал не подходят, можете еще прикрепить эту папку к проекту

**Comment by spvik** [comment]
Все сделал, заработало, отличная разработка, огромное вам спасибо, есть только один вопрос, почему то не срабатывают команды которые посылаю, только Ping работает, на остальные не отвечает, пробовал свои сделать, с простым текстом, тоже тишина

**Comment by gihar** [comment]
У вас как заработало, получилось скомпилировать, или мои dll подошли?

Команды я чё-то не доделал, как задумывал вначале. Поигрался и бросил. Мне нужно было уведомление о сделках, а оно работает.

Сейчас отрабатывать должны две "команды" Ri" и "Usd", по этим запросам посылаются текущие котировки фьючерса на индекс РТС и курс доллара USD_TOM. Чтобы эти команды работали в квике в таблицу текущих параметров должны быть выведены соответствующие инструменты.

**Comment by spvik** [comment]
С командами разобрался, нужно чтоб файл telegram.lua был в кодировке utf-8, не смог компилировал luasec, и оказалось библиотеке не нужны, Нужно в папке где лежит скрипт создать папку "ssl", и туда поместить два файла из luasec - ssl.lua, https.lua, но вашу ssl.dll на всякий случай оставил в каталоге со скриптом
Еще пришлось перерыть весь интернет в поисках JSON.lua на который ссылаются из luasec, штук 40 перебрал

**Comment by mlapov** [comment]
Здравствуйте. Пытаюсь воссоздать Ваш механизм. Робот выдает ошибки на следуюшие строки в файле https.lua из Luasec 
         self.sock = try(ssl.wrap(self.sock, params))
         try(self.sock:dohandshake())
Ошибка
.\ssl\https.lua:91: attempt to index upvalue 'ssl' (a boolean value)
и
.\ssl\https.lua:92: attempt to call method 'dohandshake' (a nil value)

Вроде понял, что ssl.wrap() и dohandshake() это какие-то функции из luasec (https://github.com/brunoos/luasec/wiki/LuaSec-0﻿.6), но почему они не проходят и проходят другие не могу понять. Толи нужно еще какие-нибудь библиотеки подцеплять
